//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POSTDATAEntities : DbContext
    {
        public POSTDATAEntities()
            : base("name=POSTDATAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TBL_ADDRESS> TBL_ADDRESS { get; set; }
        public DbSet<TBL_ADS> TBL_ADS { get; set; }
        public DbSet<TBL_CATEGORY> TBL_CATEGORY { get; set; }
        public DbSet<TBL_COMMENT> TBL_COMMENT { get; set; }
        public DbSet<TBL_CONTACT> TBL_CONTACT { get; set; }
        public DbSet<TBL_FAV_LOGO_TITLE> TBL_FAV_LOGO_TITLE { get; set; }
        public DbSet<TBL_LOG> TBL_LOG { get; set; }
        public DbSet<TBL_META> TBL_META { get; set; }
        public DbSet<TBL_POST> TBL_POST { get; set; }
        public DbSet<TBL_POST_IMAGE> TBL_POST_IMAGE { get; set; }
        public DbSet<TBL_POST_TAG> TBL_POST_TAG { get; set; }
        public DbSet<TBL_PROCESS_TYPE> TBL_PROCESS_TYPE { get; set; }
        public DbSet<TBL_SOCIAL_MEDIA> TBL_SOCIAL_MEDIA { get; set; }
        public DbSet<TBL_USER> TBL_USER { get; set; }
        public DbSet<TBL_VIDEO> TBL_VIDEO { get; set; }
    }
}
