//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PROCESS_TYPE
    {
        public TBL_PROCESS_TYPE()
        {
            this.TBL_LOG = new HashSet<TBL_LOG>();
        }
    
        public int ID { get; set; }
        public string ProcessName { get; set; }
    
        public virtual ICollection<TBL_LOG> TBL_LOG { get; set; }
    }
}
