//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER
    {
        public TBL_USER()
        {
            this.TBL_ADDRESS = new HashSet<TBL_ADDRESS>();
            this.TBL_ADS = new HashSet<TBL_ADS>();
            this.TBL_CATEGORY = new HashSet<TBL_CATEGORY>();
            this.TBL_COMMENT = new HashSet<TBL_COMMENT>();
            this.TBL_CONTACT = new HashSet<TBL_CONTACT>();
            this.TBL_FAV_LOGO_TITLE = new HashSet<TBL_FAV_LOGO_TITLE>();
            this.TBL_LOG = new HashSet<TBL_LOG>();
            this.TBL_META = new HashSet<TBL_META>();
            this.TBL_POST = new HashSet<TBL_POST>();
            this.TBL_POST_IMAGE = new HashSet<TBL_POST_IMAGE>();
            this.TBL_POST_TAG = new HashSet<TBL_POST_TAG>();
            this.TBL_SOCIAL_MEDIA = new HashSet<TBL_SOCIAL_MEDIA>();
            this.TBL_VIDEO = new HashSet<TBL_VIDEO>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string NameSurname { get; set; }
        public string ImagePath { get; set; }
        public bool isAdmin { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public System.DateTime AddDate { get; set; }
        public int LastUpdateUserID { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual ICollection<TBL_ADDRESS> TBL_ADDRESS { get; set; }
        public virtual ICollection<TBL_ADS> TBL_ADS { get; set; }
        public virtual ICollection<TBL_CATEGORY> TBL_CATEGORY { get; set; }
        public virtual ICollection<TBL_COMMENT> TBL_COMMENT { get; set; }
        public virtual ICollection<TBL_CONTACT> TBL_CONTACT { get; set; }
        public virtual ICollection<TBL_FAV_LOGO_TITLE> TBL_FAV_LOGO_TITLE { get; set; }
        public virtual ICollection<TBL_LOG> TBL_LOG { get; set; }
        public virtual ICollection<TBL_META> TBL_META { get; set; }
        public virtual ICollection<TBL_POST> TBL_POST { get; set; }
        public virtual ICollection<TBL_POST_IMAGE> TBL_POST_IMAGE { get; set; }
        public virtual ICollection<TBL_POST_TAG> TBL_POST_TAG { get; set; }
        public virtual ICollection<TBL_SOCIAL_MEDIA> TBL_SOCIAL_MEDIA { get; set; }
        public virtual ICollection<TBL_VIDEO> TBL_VIDEO { get; set; }
    }
}
