//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_POST
    {
        public TBL_POST()
        {
            this.TBL_COMMENT = new HashSet<TBL_COMMENT>();
            this.TBL_POST_IMAGE = new HashSet<TBL_POST_IMAGE>();
            this.TBL_POST_TAG = new HashSet<TBL_POST_TAG>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string ShortContent { get; set; }
        public string PostContent { get; set; }
        public int CategoryID { get; set; }
        public int ViewCount { get; set; }
        public string SeoLink { get; set; }
        public bool Slider { get; set; }
        public bool Area1 { get; set; }
        public bool Area2 { get; set; }
        public bool Area3 { get; set; }
        public bool Notification { get; set; }
        public string LanguageName { get; set; }
        public System.DateTime AddDate { get; set; }
        public int AddUserID { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int LastUpdateUserID { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual TBL_CATEGORY TBL_CATEGORY { get; set; }
        public virtual ICollection<TBL_COMMENT> TBL_COMMENT { get; set; }
        public virtual ICollection<TBL_POST_IMAGE> TBL_POST_IMAGE { get; set; }
        public virtual ICollection<TBL_POST_TAG> TBL_POST_TAG { get; set; }
        public virtual TBL_USER TBL_USER { get; set; }
    }
}
